### PR TITLE
Cointelli file format

### PR DESCRIPTION
**Pull request by ozioeh**
Hi I'm developer of cointelli.
I created PR again.

### CODE REVIEW

**Comment by ozioeh** [comment]
Thank you

**Comment by hodgerpodger** [comment]
Thanks for the contribution! 

One question: do you have any thoughts if I add the transaction hash (txid) to the csv comment field?
  * Example: comment field = row.comment + " " row.txid

You'll know better than me if the comment field is used/unused in the cointelli website (latter case I'll omit txid to reduce noise text) but generally it's helpful to know the transaction hash, especially when debugging accounts.

**Comment by hodgerpodger** [comment]
@ozioeh

**Comment by ozioeh** [comment]
Currently, cointelli doesn't use the comment field of csv, but I think it
is helpful to debug as you said.
Please add txid to comment.
Thank you.

**Comment by hodgerpodger** [comment]
Thanks @ozioeh.

2nd question as I'm testing: looks like this lp deposit transaction "failed" on import.  I'm guessing it's an unrecognized currency or doesn't like underscores in currencies for LP_mAPPL_UST?

Here's the test CSV contents:

Timestamp,Type,Out Currency,Out Quantity,In Currency,In Quantity,Fee Currency,Fee Quantity,Comments
05/05/2021 03:47:56,Trade,mAAPL,0.76689,LP_mAAPL_UST,4.2148775,UST,0.509803,lp_deposit  7890E1CB8C52ABC35DD7512CD23426DF252E4A6A5D5B91511CD21EF15CA301DC
05/05/2021 03:47:56,Trade,UST,99.700703,LP_mAAPL_UST,4.2148775,,,lp_deposit  7890E1CB8C52ABC35DD7512CD23426DF252E4A6A5D5B91511CD21EF15CA301DC

**Comment by ozioeh** [comment]
Ah, did you test with Cointelli website ?
Previously, our field engineer added  Staketax's default file format.
So, if you want to test, you should choose any exchange and select "Use
Template".

**Comment by hodgerpodger** [comment]
Thanks for response.  Yeah tested with Cointelli website.  I think it my user error as a subsequent test was fine.

**Comment by hodgerpodger** [comment]
Alrighty, cointelli CSVs are deployed and live on stake.tax!  Thanks for the contribution.  Also, saw that you originally supported stake.tax default CSVs--very cool to see on my end.

**Comment by ozioeh** [comment]
Wow.
You are so fast.
Thank you so much.

**Pull request merged**
