### PR TITLE
feat: add support for regen network

### PR DESCRIPTION
**Pull request by clevinson**
Following basics outlined in https://github.com/hodgerpodger/staketaxcsv/pull/185

Happy to add any pieces if I missed something.

Do chains added here automatically get added as well to http://stake.tax website?

### CODE REVIEW

**Comment by hodgerpodger** [comment]
🔥 Very cool.  Thanks for the contribution!

Yup, it's not an automated linkage to stake.tax but it's a fairly quick manual process and decided on a case-by-case basis.  

With that said, I'm guessing you'll see REGEN live on stake.tax within a few days, after establishing some private internal testing for it and just gaining some basic familiarity with its ecosystem.

**Comment by hodgerpodger** [comment]
Great stuff.  Looks good after some testing

**Comment by hodgerpodger** [comment]
Alrighty deployed to stake.tax!  I'll do a little announcement early next week.

**Comment by clevinson** [comment]
Thanks! 

What are you using for a public RPC node?

**Comment by hodgerpodger** [comment]
one of these: https://github.com/cosmos/chain-registry/blob/master/regen/chain.json

Oh, didn't realize until now you're a part of the Regen Network team!  Cool.

**Pull request merged**
