### PR TITLE
Added significant functionality for Terra

### PR DESCRIPTION
**Pull request by wengzilla**
Updated functionality includes:
* Mirror auctions
* Mirror repays with no withdrawals
* Anchor liquidations
* LOOP DEX LP staking
* Valkyrie staking
* MINE launchpad airdrops
* Backwards compatibility with columbus-4 Anchor borrowing

### CODE REVIEW

**Comment by hodgerpodger** [comment]
Thanks!  Awesome stuff with the anchor borrow fee fix and lots of new support.  

On a side note, if you have smart contract addresses or txids (twitter DM @staketax or support@stake.tax) examples, it'd help me to build private repo test cases.  Please don't feel obliged on this last point.  You've already done plenty.  Just asking if convenient.

**Comment by hodgerpodger** [comment]
Oh, and feel free to suggest / advise on codebase/repo.  I'm curious if there's any painful things as a contributor.

**Comment by wengzilla** [comment]
Thanks so much for putting the repo together! I think the overall architecture is really nice. It's *very* easy for a new contributor to follow along and understand what pieces need to be changed.

There's a couple of things that I'm noticing as I make changes (I'm making more as we speak) that I think could be really helpful:
- Tests (with random txids) - I've noticed that many of the DEXs use a common format; some however, have made minor tweaks and it's scary to change / refactor without knowing whether or not you're affecting anything else that might happen to use that format, but did not make those same tweaks.
- A framework for backwards compatibility - Anchor made a switch over to v2 contracts in 2021 and I'm noticing that it's a huge pain wrt code... It's basically a bunch of if/else to see whether it's the new format or the old format. Not sure what the best way to handle this going forward would be (e.g., key on contract address?) but it's worth thinking about. I shudder to think about what the code looks like when columbus-6 comes out.

I'll be back with more pull requests!

**Comment by hodgerpodger** [comment]
Thanks again for the changes 🔥  and these insights. 

Tests: Ah ok, so there's anxiety around this.  Hm at least in the short term I'll see if I can add a note to contributors that private tests are run for most txs types and perfection without those tests is not expected.  Long term, I haven't really solved the problem of tests without exposing data that would betray trust (perhaps selecting random txids per contract based on public code or something else i haven't thought of).

Framework: Yeah .... one problem at a time haha.  There does seem to be more consistency now in data (wasm data especially) so I wonder if there is a nice generalized solution now that wasn't possible when I began work on this during col4.  Thanks for this insight.  Gotta think about this one on how to organize in a nice way.

**Pull request merged**
