### PR TITLE
Terra updates

### PR DESCRIPTION
**Pull request by wengzilla**
* Better Mirror borrow fee handling
* Using ID to represent bETH to avoid symbol collision
* Removing Anchor fees from repays during liquidation

### CODE REVIEW

**Comment by wengzilla** [comment]
Has this already been merged?

**Comment by hodgerpodger** [comment]
Ah no don't think so. Was looking for a reply on the make_margin_fee question is all

**Comment by wengzilla** [comment]
So sorry I haven't gotten back around to this. What is the "make_margin_fee" question?

**Comment by hodgerpodger** [comment]
Ah, was asking if make_margin_fee() can be changed to make_spend_fee_tx()?  Custom tx generally shouldn't be used unless it's too difficult to use one of the exportable transactions (custom tx are more of a fallback when unsure about a solution).  

Seems like this implementation is correct/complete for this contract?  In which case make_spend_fee_tx() might be more appropriate?  More of a question and just wanted to confirm since I'm not intimately familiar with many applications.

**Comment by wengzilla** [comment]
I modified it. Koinly has a separate type for margin fees, which I thought was more appropriate for Mirror, but I think it's all treated the same.

**Pull request merged**
