### PR TITLE
Use a single session for API requests

### PR DESCRIPTION
**Pull request by jumperavocado**
Use a single session for API requests to avoid excessive connections. Where possible I've used the Borg pattern to simplify things, otherwise the Singleton class is used.

I've tested the changes on some blockchains. I believe you have a good test coverage for all these blockchains, can you please double check and run the tests to make sure I didn't break anything?

### CODE REVIEW

**Comment by hodgerpodger** [comment]
Wowsers!  Thanks!

Yup, will do on the testing/merging within a day (working on a large terra change atm is all).

**Comment by jumperavocado** [comment]
No worries! Actually ditched the usage of Singleton in this case, as it looked to me prone to accidental side effects. Borg pattern all the way.

**Comment by hodgerpodger** [comment]
Hah!  How apt--I watched a Picard tv show episode with lots of Borg yesterday.

**Comment by hodgerpodger** [comment]
Alrighty added a little fix, put into new PR, and merged: https://github.com/hodgerpodger/staketaxcsv/pull/110

Closing for this reason.

**Pull request closed without merging**
