### PR TITLE
Add terraswap route swap support (for bPSI-DP-24m)

### LINKED ISSUE #118: Handling of bPSI DP 24m trades
Hi,

I've noticed that the bPSI token / trades are not properly reported. Both psi -> bPSI and the terraswap router from UST -> bPSI.

### PR DESCRIPTION
**Pull request by laine-ust**
# This PR will:

- Add terraswap route swap support, initially with focus on supporting bPSI-DP-24M trades
- Add "events from log" helper to extract events from log messages
   
## testing

Two random transactions picked up from the route-swap contract:
- https://finder.extraterrestrial.money/mainnet/tx/DB5A846ABE56585EF99906108C4251F508FCCDDCD15629D318B8AA8FF907CAE5
- https://finder.extraterrestrial.money/mainnet/tx/7090E0A61AFAF52D4597B853C8063FC5F33E87A215FCC7953C7D70DC83A289EE

Close #118

### CODE REVIEW

**Comment by laine-ust** [comment]
@hodgerpodger still WIP but creating PR early for feedback. Python is not my strongest language so there might be things to improve, just let me know! :)

**Comment by laine-ust** [comment]
I think it's ready now.

**Comment by hodgerpodger** [comment]
Yup, I stand corrected from my first comment.  Great stuff.  All tests passed--and I have a few tests specificilly for "execute_swap_operations".  

I'll add some private tests to detect regression and merge/deploy in a little bit.

**Comment by Mylros** [comment]
is this one supposed to handle #46 ?

**Comment by laine-ust** [comment]
> is this one supposed to handle #46 ?

Not intentionally, but at least now the token info is in place.
I might have time to look at it during the weekend if there are no other takers 😊

**Pull request merged**
