### PR TITLE
Integrate KYVE Network

### PR DESCRIPTION
**Pull request by fabianriewe**
This PR introduces support for KYVE Network. I have followed the BLD implementation and made the needed changes.

### CODE REVIEW

**Comment by hodgerpodger** [comment]
Thanks!  I'll try to integrate it this week.

**Review by hodgerpodger — CHANGES_REQUESTED** [review]
Thanks for the work. I think you need to rewrite to use api_lcd_v2.py like report_evmos.py because it likely breaks many reports if changing api_lcd.py. 

I'll probably need to change guides/instructions on this aspect (prettty recent development)

**Comment by fabianriewe** [comment]
Thanks, I have updated to the latest version of this class

**Comment by hodgerpodger** [comment]
🔥  

I'll work to get this into stake.tax this week.

**Pull request merged**
